In [1]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.1.a)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
number = float(input("Enter a number: "))

# Check if the number is positive, negative, or zero
if number > 0:
    print("The number is Positive.")
elif number < 0:
    print("The number is Negative.")
else:
    print("The number is Zero.")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter a number: 10
The number is Positive.

In [9]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.1.b)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
numbers = list(map(int, input("Enter numbers separated by space: ").split()))

sum_of_odds = 0
product_of_evens = 1
has_even = False

for num in numbers:
    if num % 2 == 0:
        product_of_evens *= num
        has_even = True
    else:
        sum_of_odds += num

if not has_even:
    product_of_evens = 0

print("Sum of odd numbers:", sum_of_odds)
print("Product of even numbers:", product_of_evens)

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter numbers separated by space: 9 7
Sum of odd numbers: 16
Product of even numbers: 0

In [10]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.1.c)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
number = int(input("Enter a number to find its factorial: "))

factorial = 1

if number < 0:
    print("Factorial is not defined for negative numbers.")
elif number == 0:
    print("The factorial of 0 is 1.")
else:
    for i in range(1, number + 1):
        factorial *= i
    print(f"The factorial of {number} is {factorial}.")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter a number to find its factorial: 7
The factorial of 7 is 5040.

In [11]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.1.d)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
n_terms = int(input("Enter the number of terms: "))

if n_terms <= 0:
    print("Please enter a positive integer.")
else:
    a, b = 0, 1
    print("Fibonacci sequence:")
    for _ in range(n_terms):
        print(a, end=" ")
        a, b = b, a + b

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter the number of terms: 12
Fibonacci sequence:
0 1 1 2 3 5 8 13 21 34 55 89

In [12]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.1.e)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
number = int(input("Enter the number for the multiplication table: "))

table_range = int(input("Enter the range for the multiplication table (e.g., 10): "))

print(f"\nMultiplication Table of {number}:")

for i in range(1, table_range + 1):
    print(f"{number} x {i} = {number * i}")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter the number for the multiplication table: 9
Enter the range for the multiplication table (e.g., 10): 10

Multiplication Table of 9:
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90

In [13]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.1.f)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
number = int(input("Enter a number to check if it's an Armstrong number: "))

temp = number
sum_of_cubes = 0

while temp > 0:
    digit = temp % 10
    sum_of_cubes += digit ** 3
    temp //= 10

if sum_of_cubes == number:
    print(f"{number} is an Armstrong number.")
else:
    print(f"{number} is not an Armstrong number.")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter a number to check if it's an Armstrong number: 23
23 is not an Armstrong number.

In [14]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.1.g)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
number = int(input("Enter a number: "))

if number > 1:
    for i in range(2, number):
        if number % i == 0:
            print(f"{number} is not a prime number.")
            break
    else:
        print(f"{number} is a prime number.")
else:
    print(f"{number} is not a prime number.")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter a number: 19
19 is a prime number.

In [15]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.1.h)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
number = int(input("Enter a number: "))

if number % 2 == 0:
    print(f"{number} is an Even number.")
else:
    print(f"{number} is an Odd number.")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter a number: 12
12 is an Even number.

In [16]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.2)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
# List of temperatures in Celsius for 10 cities
celsius_temperatures = [25, 30, 15, 20, 35, 10, 5, 40, 28, 22]

# Lambda function to convert Celsius to Fahrenheit
celsius_to_fahrenheit = lambda c: (c * 9/5) + 32

# Use map to apply the conversion to all temperatures
fahrenheit_temperatures = list(map(celsius_to_fahrenheit, celsius_temperatures))

# Print the results
print("Temperatures in Celsius:", celsius_temperatures)
print("Temperatures in Fahrenheit:", fahrenheit_temperatures)

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Temperatures in Celsius: [25, 30, 15, 20, 35, 10, 5, 40, 28, 22]
Temperatures in Fahrenheit: [77.0, 86.0, 59.0, 68.0, 95.0, 50.0, 41.0, 104.0, 82.4, 71.6]

In [17]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.3)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
from functools import reduce

# Input: Accept a list of numbers from the user
numbers = list(map(int, input("Enter numbers separated by space: ").split()))

# Check if the list has more than 3 numbers
if len(numbers) > 3:
    # Use map to filter even numbers (set odd numbers to 0)
    even_numbers = list(map(lambda x: x if x % 2 == 0 else 0, numbers))

    # Use reduce to calculate the sum of even numbers
    sum_of_evens = reduce(lambda x, y: x + y, even_numbers)

    print("Even numbers:", [num for num in numbers if num % 2 == 0])
    print("Sum of even numbers:", sum_of_evens)
else:
    print("Input must contain more than 3 numbers.")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter numbers separated by space: 9 7 5
Input must contain more than 3 numbers.

In [18]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.4.1)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
class OddNumberException(Exception):
    def __init__(self, message="The number is odd"):
        self.message = message
        super().__init__(self.message)

def check_even_odd(number):
    try:
        if number % 2 != 0:
            raise OddNumberException(f"{number} is an odd number.")
        else:
            print(f"{number} is an even number.")
    except OddNumberException as e:
        print(e)

try:
    num = int(input("Enter a number: "))
    check_even_odd(num)
except ValueError:
    print("Invalid input! Please enter an integer.")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter a number: 23
23 is an odd number.

In [19]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.4.2)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
class NotPrimeException(Exception):
    def __init__(self, message="The number is not prime"):
        self.message = message
        super().__init__(self.message)

def check_prime(number):
    try:
        if number <= 1:
            raise NotPrimeException(f"{number} is not a prime number (must be greater than 1).")
        for i in range(2, int(number ** 0.5) + 1):
            if number % i == 0:
                raise NotPrimeException(f"{number} is not a prime number (divisible by {i}).")
        print(f"{number} is a prime number.")
    except NotPrimeException as e:
        print(e)

try:
    num = int(input("Enter a number: "))
    check_prime(num)
except ValueError:
    print("Invalid input! Please enter an integer.")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter a number: 12
12 is not a prime number (divisible by 2).

In [20]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.4.3)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
class ComparisonException(Exception):
    def __init__(self, message):
        self.message = message
        super().__init__(self.message)

def compare_numbers(num1, num2):
    try:
        if num1 > num2:
            raise ComparisonException(f"{num1} is larger than {num2}.")
        elif num1 < num2:
            raise ComparisonException(f"{num1} is smaller than {num2}.")
        else:
            raise ComparisonException(f"{num1} is equal to {num2}.")
    except ComparisonException as e:
        print(e)

try:
    number1 = int(input("Enter the first number: "))
    number2 = int(input("Enter the second number: "))
    compare_numbers(number1, number2)
except ValueError:
    print("Invalid input! Please enter valid integers.")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter the first number: 12
Enter the second number: 10
12 is larger than 10.

In [21]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.5)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
def check_age(age):
    try:
        if age < 0 or age > 120:
            raise ValueError("Invalid age! Age must be between 0 and 120.")
        else:
            print(f"Age {age} is valid.")
    except ValueError as e:
        print(e)

try:
    user_age = int(input("Enter your age: "))
    check_age(user_age)
except ValueError:
    print("Invalid input! Please enter a valid integer.")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter your age: 21
Age 21 is valid.

In [22]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.6)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
try:
    print("Trying to divide 10 by 0...")
    result = 10 / 0

except ZeroDivisionError as e:
    print(f"Caught a ZeroDivisionError: {e}")

try:
    print("\nTrying to convert 'abc' to an integer...")
    num = int("abc")
except ValueError as e:
    print(f"Caught a ValueError: {e}")

try:
    print("\nTrying to access an invalid index in a list...")
    my_list = [1, 2, 3]
    print(my_list[5])
except IndexError as e:
    print(f"Caught an IndexError: {e}")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Trying to divide 10 by 0...
Caught a ZeroDivisionError: division by zero

Trying to convert 'abc' to an integer...
Caught a ValueError: invalid literal for int() with base 10: 'abc'

Trying to access an invalid index in a list...
Caught an IndexError: list index out of range

In [2]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.7)
# arithmetic.py
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
def add(a, b):
    """Returns the sum of two numbers."""
    return a + b

def subtract(a, b):
    """Returns the difference between two numbers."""
    return a - b

def multiply(a, b):
    """Returns the product of two numbers."""
    return a * b

def divide(a, b):
    """Returns the division of two numbers. Raises an error for division by zero."""
    if b == 0:
        return "Division by zero is not allowed."
    return a / b


# main_program.py

# Import the arithmetic module
import arithmetic

# Perform arithmetic operations
a = float(input("Enter the first number: "))
b = float(input("Enter the second number: "))

print(f"Addition: {arithmetic.add(a, b)}")
print(f"Subtraction: {arithmetic.subtract(a, b)}")
print(f"Multiplication: {arithmetic.multiply(a, b)}")
print(f"Division: {arithmetic.divide(a, b)}")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

ModuleNotFoundError: No module named 'arithmetic'

In [23]:
#WAP to create Operator package and perform logical operations.
print("Name:Jatin Vinayak Mahajan")
print("Roll No:24235")
# Q.8)
# Logical operations module

def logical_and(a, b):
    """Returns the logical AND of two boolean values."""
    return a and b

def logical_or(a, b):
    """Returns the logical OR of two boolean values."""
    return a or b

def logical_not(a):
    """Returns the logical NOT of a boolean value."""
    return not a

# Main program to perform logical operations
def perform_logical_operations():
    print("Logical Operations Program")
    print("1. Logical AND")
    print("2. Logical OR")
    print("3. Logical NOT")

    try:
        choice = int(input("Enter your choice (1-3): "))
        if choice == 1:
            a = bool(int(input("Enter the first boolean value (0 or 1): ")))
            b = bool(int(input("Enter the second boolean value (0 or 1): ")))
            print(f"Result of AND operation: {logical_and(a, b)}")
        elif choice == 2:
            a = bool(int(input("Enter the first boolean value (0 or 1): ")))
            b = bool(int(input("Enter the second boolean value (0 or 1): ")))
            print(f"Result of OR operation: {logical_or(a, b)}")
        elif choice == 3:
            a = bool(int(input("Enter a boolean value (0 or 1): ")))
            print(f"Result of NOT operation: {logical_not(a)}")
        else:
            print("Invalid choice! Please select from 1 to 3.")
    except ValueError as e:
        print(f"Invalid input: {e}")

# Run the program
if __name__ == "__main__":
    perform_logical_operations()

Name:Jatin Vinayak Mahajan
Roll No:24235
Logical Operations Program
1. Logical AND
2. Logical OR
3. Logical NOT
Enter your choice (1-3): 3
Enter a boolean value (0 or 1): 1
Result of NOT operation: False

In [4]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.9)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
def sum_of_even_numbers(n):
    """Generator function to yield the sum of the first n even numbers."""
    total = 0
    for i in range(1, n + 1):
        even_number = 2 * i
        total += even_number
        yield total

# Example usage
n = int(input("Enter the number of even numbers to sum: "))
print(f"The sum of the first {n} even numbers:")

# Use the generator
for result in sum_of_even_numbers(n):
    print(result)

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter the number of even numbers to sum: 12
The sum of the first 12 even numbers:
2
6
12
20
30
42
56
72
90
110
132
156

In [24]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.10)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
def square_decorator(func):
    """Decorator to calculate the square of a number."""
    def wrapper(n):
        result = func(n)
        squared = result ** 2
        print(f"Square of {result} is {squared}")
        return squared
    return wrapper

def double_decorator(func):

    """Decorator to double the result."""
    def wrapper(n):
        result = func(n)
        doubled = result * 2
        print(f"Double of {result} is {doubled}")
        return doubled
    return wrapper

@square_decorator
@double_decorator
def number(n):
    """Returns the original number."""
    return n

num = int(input("Enter a number: "))
result = number(num)
print(f"Final result: {result}")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter a number: 21
Double of 21 is 42
Square of 42 is 1764
Final result: 1764

In [25]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.11)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
from abc import ABC, abstractmethod

class Shape(ABC):
    """Abstract base class for shapes."""

    @abstractmethod
    def area(self):
        """Abstract method to calculate the area of the shape."""
        pass

    @abstractmethod
    def perimeter(self):
        """Abstract method to calculate the perimeter of the shape."""
        pass

    def display_details(self):
        """Display the details of the shape."""
        print(f"Area: {self.area()}")
        print(f"Perimeter: {self.perimeter()}")

class Rectangle(Shape):
    """Concrete class for a rectangle."""

    def __init__(self, length, width):
        self.length = length
        self.width = width

    def area(self):
        return self.length * self.width

    def perimeter(self):
        return 2 * (self.length + self.width)

# Example usage
length = float(input("Enter the length of the rectangle: "))
width = float(input("Enter the width of the rectangle: "))

rect = Rectangle(length, width)
print("\nRectangle Details:")
rect.display_details()

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter the length of the rectangle: 21
Enter the width of the rectangle: 10

Rectangle Details:
Area: 210.0
Perimeter: 62.0

In [26]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.12)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
class BankAccount:
    """A class to represent a bank account with encapsulation."""

    def __init__(self, account_holder, balance=0.0):
        self.__account_holder = account_holder  # Private attribute
        self.__balance = balance  # Private attribute

    # Getter for account holder
    def get_account_holder(self):
        return self.__account_holder

    # Setter for account holder
    def set_account_holder(self, name):
        self.__account_holder = name

    # Getter for balance
    def get_balance(self):
        return self.__balance

    # Method to deposit money
    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
            print(f"Deposited: {amount}. New Balance: {self.__balance}")
        else:
            print("Deposit amount must be positive.")

    # Method to withdraw money
    def withdraw(self, amount):
        if amount > 0:
            if self.__balance >= amount:
                self.__balance -= amount
                print(f"Withdrawn: {amount}. Remaining Balance: {self.__balance}")
            else:
                print("Insufficient balance.")
        else:
            print("Withdrawal amount must be positive.")

# Example usage
account = BankAccount("John Doe", 1000.0)

print("Account Holder:", account.get_account_holder())
print("Current Balance:", account.get_balance())

account.deposit(500)
account.withdraw(300)
account.withdraw(1500)  # Attempt to overdraw
account.set_account_holder("Jane Doe")
print("Updated Account Holder:", account.get_account_holder())

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Account Holder: John Doe
Current Balance: 1000.0
Deposited: 500. New Balance: 1500.0
Withdrawn: 300. Remaining Balance: 1200.0
Insufficient balance.
Updated Account Holder: Jane Doe

In [27]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.13)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
class A:
    """Class to store employee details."""
    def __init__(self, emp_id, name, designation, department):
        self.emp_id = emp_id
        self.name = name
        self.designation = designation
        self.department = department

    def display_employee_details(self):
        print("Employee Details:")
        print(f"ID: {self.emp_id}")
        print(f"Name: {self.name}")
        print(f"Designation: {self.designation}")
        print(f"Department: {self.department}")


class B(A):
    """Class to calculate gross salary."""
    def __init__(self, emp_id, name, designation, department, basic_salary, da, hra, ta):
        super().__init__(emp_id, name, designation, department)
        self.basic_salary = basic_salary
        self.da = da
        self.hra = hra
        self.ta = ta
        self.gross_salary = 0

    def calculate_gross_salary(self):
        self.gross_salary = self.basic_salary + self.da + self.hra + self.ta
        return self.gross_salary

    def display_gross_salary(self):
        print(f"Gross Salary: {self.gross_salary}")


class C(B):
    """Class to calculate deductions."""
    def __init__(self, emp_id, name, designation, department, basic_salary, da, hra, ta, income_tax, other_deductions):
        super().__init__(emp_id, name, designation, department, basic_salary, da, hra, ta)
        self.income_tax = income_tax
        self.other_deductions = other_deductions
        self.total_deductions = 0

    def calculate_deductions(self):
        self.total_deductions = self.income_tax + self.other_deductions
        return self.total_deductions

    def display_deductions(self):
        print(f"Total Deductions: {self.total_deductions}")


class D(C):
    """Class to calculate net salary."""
    def __init__(self, emp_id, name, designation, department, basic_salary, da, hra, ta, income_tax, other_deductions):
        super().__init__(emp_id, name, designation, department, basic_salary, da, hra, ta, income_tax, other_deductions)
        self.net_salary = 0

    def calculate_net_salary(self):
        self.net_salary = self.calculate_gross_salary() - self.calculate_deductions()
        return self.net_salary

    def display_net_salary(self):
        print(f"Net Salary: {self.net_salary}")


# Example usage
employee = D(
    emp_id=101,
    name="John Doe",
    designation="Software Engineer",
    department="IT",
    basic_salary=50000,
    da=10000,  # Dearness Allowance
    hra=8000,  # House Rent Allowance
    ta=5000,   # Travel Allowance
    income_tax=8000,
    other_deductions=2000
)

# Display employee details
employee.display_employee_details()

# Calculate and display salaries
employee.calculate_gross_salary()
employee.display_gross_salary()

employee.calculate_deductions()
employee.display_deductions()

employee.calculate_net_salary()
employee.display_net_salary()

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Employee Details:
ID: 101
Name: John Doe
Designation: Software Engineer
Department: IT
Gross Salary: 73000
Total Deductions: 10000
Net Salary: 63000

In [28]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.14)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
class Calculator:
    """Class to demonstrate both function overloading and operator overloading."""

    def add(self, *args):
        """Function overloading: adds multiple numbers."""
        return sum(args)

    def __add__(self, other):
        """Operator overloading: adds two Calculator objects."""
        return Calculator(self.add(self.value, other.value))

    def __init__(self, value=0):
        self.value = value

    def __str__(self):
        """String representation of the Calculator object."""
        return f"Calculator(value={self.value})"

# Example usage
calc1 = Calculator(10)
calc2 = Calculator(20)

# Function overloading
calc = Calculator()
print(calc.add(1, 2, 3))  # Adding three numbers: 6

# Operator overloading
calc3 = calc1 + calc2
print(calc3)  # Output: Calculator(value=30)

Name:- Jatin Vinayak Mahajan
Roll No:-24235

6
Calculator(value=30)

In [29]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.15)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
class Calculator:
    """Class to calculate the sum of two numbers."""

    def __init__(self, num1, num2):
        self.num1 = num1
        self.num2 = num2

    def calculate_sum(self):
        """Method to calculate the sum of two numbers."""
        return self.num1 + self.num2

# Example usage
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))

calc = Calculator(num1, num2)
result = calc.calculate_sum()
print(f"The sum of {num1} and {num2} is: {result}")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter the first number: 12
Enter the second number: 10
The sum of 12.0 and 10.0 is: 22.0

In [30]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.16)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
import re
import requests
from bs4 import BeautifulSoup

def scrape_emails(url):
    """Scrapes email addresses from the given URL."""
    try:
        # Send a GET request to fetch the raw HTML content
        response = requests.get(url)
        response.raise_for_status()  # Raise HTTPError for bad responses (4xx or 5xx)

        # Parse the HTML content using BeautifulSoup
        soup = BeautifulSoup(response.text, 'html.parser')
        text = soup.get_text()  # Extract the text content

        # Regular expression to find email addresses
        email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
        emails = re.findall(email_pattern, text)  # Find all email addresses in the text

        return set(emails)  # Return unique email addresses
    except requests.exceptions.RequestException as e:
        print(f"Error fetching URL: {e}")
        return []

# Example usage
if __name__ == "__main__":
    url = input("Enter the URL to scrape emails from: ")
    emails = scrape_emails(url)

    if emails:
        print("\nFound email addresses:")
        for email in emails:
            print(email)
    else:
        print("\nNo email addresses found.")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter the URL to scrape emails from: https://www.youtube.com

No email addresses found.

In [31]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.17)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
import re

def validate_email(email):
    """Validate email ID."""
    pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
    return re.match(pattern, email) is not None

def validate_password(password):
    """Validate password with the following rules:
    - At least 8 characters
    - Contains at least one uppercase letter
    - Contains at least one lowercase letter
    - Contains at least one digit
    - Contains at least one special character
    """
    pattern = r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$'
    return re.match(pattern, password) is not None

def validate_mobile_number(mobile):
    """Validate mobile number (10 digits, starting with 7, 8, or 9)."""
    pattern = r'^[789]\d{9}$'
    return re.match(pattern, mobile) is not None

def validate_url(url):
    """Validate URL."""
    pattern = r'^(https?://)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(/.*)?$'
    return re.match(pattern, url) is not None

# Example usage
if __name__ == "__main__":
    email = input("Enter an email ID: ")
    print("Valid Email" if validate_email(email) else "Invalid Email")

    password = input("Enter a password: ")
    print("Valid Password" if validate_password(password)
    else "Invalid Password")

    mobile = input("Enter a mobile number: ")
    print("Valid Mobile Number" if validate_mobile_number(mobile) else "Invalid Mobile Number")

    url = input("Enter a URL: ")
    print("Valid URL" if validate_url(url) else "Invalid URL")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Enter an email ID: jatinmahajan2979@gmail.com
Valid Email
Enter a password: Qwerty@1
Valid Password
Enter a mobile number: 8766559891
Valid Mobile Number
Enter a URL: https://www.youtube.com
Valid URL

In [32]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.18.i)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
import threading
import time

# Task 1: Print numbers
def print_numbers():
    for i in range(1, 6):
        print(f"Number: {i}")
        time.sleep(1)  # Simulate some delay

# Task 2: Print alphabets
def print_alphabets():
    for ch in 'ABCDE':
        print(f"Alphabet: {ch}")
        time.sleep(1)  # Simulate some delay

# Task 3: Print squares of numbers
def print_squares():
    for i in range(1, 6):
        print(f"Square of {i}: {i**2}")
        time.sleep(1)  # Simulate some delay

# Main function
if __name__ == "__main__":
    # Creating threads
    thread1 = threading.Thread(target=print_numbers)
    thread2 = threading.Thread(target=print_alphabets)
    thread3 = threading.Thread(target=print_squares)

    # Starting threads
    thread1.start()
    thread2.start()
    thread3.start()

    # Wait for all threads to complete
    thread1.join()
    thread2.join()
    thread3.join()

    print("All tasks completed.")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Number: 1
Alphabet: A
Square of 1: 1
Number: 2
Square of 2: 4Alphabet: B

Number: 3Alphabet: C

Square of 3: 9
Alphabet: D
Number: 4
Square of 4: 16
Alphabet: ENumber: 5

Square of 5: 25
All tasks completed.

In [33]:
# Name:- Jatin Vinayak Mahajan
# Roll No:-24235
# Q.18.ii)
print('''Name:- Jatin Vinayak Mahajan
Roll No:-24235''')
print()
import threading
import time

# Shared resource (counter)
counter = 0

# Lock for synchronization
lock = threading.Lock()

# Function to increment the counter
def increment_counter():
    global counter
    for _ in range(5):
        lock.acquire()  # Acquire the lock before modifying the counter
        try:
            temp = counter
            time.sleep(0.1)  # Simulate some work
            counter = temp + 1
            print(f"{threading.current_thread().name} incremented counter to {counter}")
        finally:
            lock.release()  # Release the lock

# Main function
if __name__ == "__main__":
    # Create threads
    thread1 = threading.Thread(target=increment_counter, name="Thread-1")
    thread2 = threading.Thread(target=increment_counter, name="Thread-2")

    # Start threads
    thread1.start()
    thread2.start()

    # Wait for threads to finish
    thread1.join()
    thread2.join()

    print(f"Final counter value: {counter}")

Name:- Jatin Vinayak Mahajan
Roll No:-24235

Thread-1 incremented counter to 1
Thread-1 incremented counter to 2
Thread-1 incremented counter to 3
Thread-1 incremented counter to 4
Thread-1 incremented counter to 5
Thread-2 incremented counter to 6
Thread-2 incremented counter to 7
Thread-2 incremented counter to 8
Thread-2 incremented counter to 9
Thread-2 incremented counter to 10
Final counter value: 10